### ISSUE TITLE
希望秒杀工具栏的位置可以拖动

### ISSUE THREAD

**Issue by beaquant** [gongjunhao/seckill#19]
希望秒杀工具栏的位置可以拖动
现在秒杀工具栏在最下面，而有点秒杀按键也在最下面，被遮挡，定位选择就有困难

**Comment by gongjunhao** [comment]
很好的建议，后续有时间，会增加这个功能，感谢使用~

**Comment by beaquant** [comment]
感谢提供。
或者说改哪里能改变其位置？我想临时改改用一下

**Comment by gongjunhao** [comment]
你可以修改这个css文件：seckill/src/css/form.css 如下这段样式
```css
#secKillForm {
    position: fixed;
    bottom: 5px;
    margin: auto;
    width: 98%;
    height: 45px;
    padding: 2px 10px;
    box-shadow: 1px 2px 2px #888888;
    border-radius: 5px;
    font-size: 12px;
    font-family: 微软雅黑 Microsoft Himalaya Consolas;
    overflow: hidden;
    background: -webkit-linear-gradient(top, rgba(255, 175, 75, 1) 0%, rgba(255, 173, 10, 1) 8%, rgba(255, 146, 10, 1) 52%, rgba(255, 146, 10, 1) 96%, rgba(255, 173, 10, 1) 98%, rgba(255, 146, 10, 1) 100%);
    z-index: 2147483649;
    box-sizing:unset;
}
```

调整至你想要的位置，重新安装插件
